kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet:  |
{{ .Values.production.nginxConfig | indent 6 }}
spec:
  tls:
  - secretName: {{ .Values.name }}-tls
    hosts:
    - {{ .Values.domain }}
    - www.{{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http: &http_service
      paths:
       - path: /
        backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.production.port | default 80 }}

  # Alias domains
  - host: www.{{ .Values.name }}
    http: *http_service
