kind: Service
apiVersion: v1
metadata:
  name: base
spec:
  selector:
    app: {{ .Values.domain }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.production.port | default 80 }}
      targetPort: http
