---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: limesdr-snapcraft-io
spec:
  selector:
    app: limesdr.snapcraft.io
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: limesdr-snapcraft-io
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: limesdr.snapcraft.io
    spec:
      containers:
        - name: limesdr-snapcraft-io
          image: prod-comms.docker-registry.canonical.com/limesdr.snapcraft.io:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
