---

kind: Service
apiVersion: v1
metadata:
  name: rendertron
spec:
  selector:
    app: rendertron
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: rendertron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rendertron
    spec:
      containers:
        - name: rendertron
          image: prod-comms.docker-registry.canonical.com/rendertron:${TAG_TO_DEPLOY}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
