---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: webteam-ircbot-canonical-com
spec:
  selector:
    app: webteam-ircbot.canonical.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: webteam-ircbot-canonical-com
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webteam-ircbot.canonical.com
    spec:
      containers:
        - name: webteam-ircbot-canonical-com
          image: prod-comms.docker-registry.canonical.com/webteam-ircbot.canonical.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: proxy-config
                optional: true
          env:
            - name: HUBOT_IRC_NICK
              value: "webbot"
            - name: HUBOT_IRC_SERVER
              value: "irc.canonical.com"
            - name: HUBOT_IRC_PORT
              value: "6697"
            - name: HUBOT_IRC_USESSL
              value: "true"
            - name: HUBOT_IRC_ROOMS
              value: "#sukha,#web-team"
            - name: HUBOT_RELEASE_NOTIFICATION_ROOMS
              value: "#web-team,#is"
            - name: HUBOT_IRC_DEBUG
              value: "true"
            - name: HUBOT_AUTH_ADMIN
              valueFrom:
                secretKeyRef:
                  name: irc-secrets
                  key: hubot-auth-admin
            - name: HUBOT_IRC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: irc-secrets
                  key: hubot-irc-password
            - name: HUBOT_RELEASE_NOTIFICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: irc-secrets
                  key: hubot-release-notification-secret
          resources:
            limits:
              memory: "128Mi"

---
