---

kind: Service
apiVersion: v1
metadata:
  name: {{ data.get('name') or get_site_name() }}
  namespace: {{ namespace }}
spec:
  selector:
    app: {{ data.get('app_name') or domain }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
