---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: manager-assets-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: manager-assets-ubuntu-com-tls
    hosts:
    - manager.assets.ubuntu.com
  rules:
  - host: manager.assets.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: manager-assets-ubuntu-com
          servicePort: 80

---
