---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: sdrsatcom-snapcraft-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: sdrsatcom-snapcraft-io-tls
    hosts:
    - sdrsatcom.snapcraft.io
  rules:
  - host: sdrsatcom.snapcraft.io
    http:
      paths:
      - path: /
        backend:
          serviceName: sdrsatcom-snapcraft-io
          servicePort: 80

---
