---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      if ($host = 'insights.staging.ubuntu.com' ) {
        rewrite ^ https://staging.ubuntu.com/blog$request_uri? permanent;
      }
      if ($host = 'blog.staging.ubuntu.com' ) {
        rewrite ^ https://staging.ubuntu.com/blog$request_uri? permanent;
      }
      if ($host != 'staging.ubuntu.com' ) {
        rewrite ^ https://staging.ubuntu.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: staging-ubuntu-com-tls
    hosts:
    - staging.ubuntu.com
  - secretName: insights-staging-ubuntu-com-tls
    hosts:
    - insights-staging.ubuntu.com
  - secretName: staging-ubuntu-com-tls
    hosts:
    - staging.ubuntu.com
  - secretName: blog-staging-ubuntu-com-tls
    hosts:
    - blog.staging.ubuntu.com
  rules:
  - host: staging.ubuntu.com
    http: &ubuntu-com_service
      paths:
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80
  
  # Alias domains
  - host: www.staging.ubuntu.com
    http: *ubuntu-com_service
  - host: blog.staging.ubuntu.com
    http: *ubuntu-com_service
  - host: insights.staging.ubuntu.com
    http: *ubuntu-com_service

---
